apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinepik-keycloak-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinepik-keycloak
  template:
    metadata:
      labels:
        app: cinepik-keycloak
    spec:
      containers:
        - image: sebam/cinepik-keycloak:latest
          name: cinepik-keycloak
          command: ['/opt/keycloak/bin/kc.sh']
          args: ['--verbose', 'start-dev', '--import-realm']
          env:
            # Inject variables from a Kuberentes ConfigMap
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KEYCLOAK_PORT
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_PORT

          ports:
            - containerPort: 8080
              name: server
          volumeMounts:
            - name: seed
              mountPath: '/opt/keycloak/data/import'
              readOnly: true
      volumes:
        - name: seed
          configMap:
            name: cinepik-realm
---
apiVersion: v1
kind: Service
metadata:
  name: cinepik-keycloak
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: server
  selector:
    app: cinepik-keycloak
