apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinepik-keycloak-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinepik-keycloak
  template:
    metadata:
      labels:
        app: cinepik-keycloak
    spec:
      containers:
        - image: sebam/cinepik-keycloak:latest
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 250m
              memory: 1Gi
          name: cinepik-keycloak
          command: ['/opt/keycloak/bin/kc.sh']
          args: ['--verbose', 'start-dev', '--import-realm']
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-credentials
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KEYCLOAK_PORT
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: KEYCLOAK_PORT
            - name: KC_HEALTH_ENABLED
              value: 'true'
            - name: KC_METRICS_ENABLED
              value: 'true'
            - name: KC_HOSTNAME_PATH
              value: 'keycloak'

          ports:
            - containerPort: 8080
              name: server
          volumeMounts:
            - name: seed
              mountPath: '/opt/keycloak/data/import'
              readOnly: true
          # livenessProbe:
          #   httpGet:
          #     path: /health/live
          #     port: server
          #   initialDelaySeconds: 60
          #   periodSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /health/ready
          #     port: server
          #   initialDelaySeconds: 60
          #   periodSeconds: 5
      volumes:
        - name: seed
          configMap:
            name: cinepik-realm
